format = """
[](#814b7B)\
$username\
$os\
[](bg:#C85C73 fg:#814b7B)\
$directory\
[](fg:#C85C73 bg:#DE8968)\
$git_branch\
$git_status\
[](fg:#DE8968 bg:#6CA2BF)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$python\
$rust\
$scala\
[](fg:#6CA2BF bg:#2AA5A9)\
$docker_context\
[](fg:#2AA5A9 bg:#456E8D)\
$time\
[ ](fg:#456E8D)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#814b7B"
style_root = "bg:#814b7B"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
format = "[on $symbol ]($style)"
style = "bg:#814b7B"
disabled = false                 # Disabled by default

[os.symbols]
Arch = "󰣇 "
EndeavourOS = " "
Fedora = "󰣛 "

[directory]
style = "bg:#C85C73"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#6CA2BF"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#6CA2BF"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#2AA5A9"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#6CA2BF"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#6CA2BF"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#DE8968"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#DE8968"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#6CA2BF"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#6CA2BF"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#6CA2BF"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#6CA2BF"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#6CA2BF"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#6CA2BF"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#6CA2BF"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "  "
style = "bg:#6CA2BF"
format = '[${symbol} (\($virtualenv\)) ]($style)'

[rust]
symbol = ""
style = "bg:#6CA2BF"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#6CA2BF"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"              # Hour:Minute Format
style = "bg:#456E8D"
format = '[ 󰋑  $time ]($style)'
