" Disable compatibility with vi which can cause unexpected issues.
set nocompatible

" Enable type file detection. Vim will be able to try to detect the type of file in use.
filetype on

" Enable plugins and load plugin for the detected file type.
filetype plugin on

" Load an indent file for the detected file type.
filetype indent on

" Turn syntax highlighting on.
syntax on

" Add numbers to each line on the left-hand side.
set number

" Add relative numbers to each line on the left-hand side.
set relativenumber

" Show matching words during a search.
set showmatch

" Use highlighting when doing a search.
set hlsearch

" Enable auto completion menu after pressing TAB.
set wildmenu
"
" Set shift width to 4 spaces.
set shiftwidth=4

" Set tab width to 4 columns.
set tabstop=4

" MAPPINGS --------------------------------------------------------------- {{{

let mapleader = " "

inoremap jk <Esc>
inoremap kj <Esc>

nnoremap ; :

" NERDTree
nnoremap <leader>e :NERDTreeToggle<CR>
nnoremap <leader>pv :NERDTreeExplore<CR>

nnoremap <leader>wh <C-w>h
nnoremap <leader>wl <C-w>l

"" FZF
nnoremap <Leader>ff :Files<CR>
nnoremap <Leader>fh :Files ~<CR>
nnoremap <Leader>h :History<CR>
nnoremap <Leader>fb :Buffers<CR>
nnoremap <Leader>fg :Rg<CR>

""" Buffers
nnoremap <silent> [b :bprevious<CR>
nnoremap <silent> ]b :bnext<CR>
nnoremap <silent> <Right> :bnext<CR>
nnoremap <silent> <Left> :bprevious<CR>
nnoremap <leader>bd :bdelete<CR>

" LSP
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gr <Plug>(coc-references)
nmap <leader>rn <Plug>(coc-rename)
nnoremap <silent> K :call CocActionAsync('doHover')<CR>
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

"VIM PLUG --------------------------------------------------------------- {{{
call plug#begin('~/.vim/plugged')

Plug 'preservim/nerdtree'

" List your plugins here
Plug 'rose-pine/vim'
Plug 'tpope/vim-sensible'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'


""LSP
Plug 'neoclide/coc.nvim', {'branch': 'release'}

"autocomplete
Plug 'tpope/vim-surround'
Plug 'jiangmiao/auto-pairs'

"Git
Plug 'airblade/vim-gitgutter'

call plug#end()

" COLOR--------------------------------------------------------------- {{{
set termguicolors
let g:disable_bg = 1
set background=dark
colorscheme rosepine_moon
